name: Docker Squash, Build and Push Multi-Platform Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  squash_and_build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install docker-squash.sh script
      run: |
        sudo curl -sL https://github.com/shinsenter/docker-squash/raw/main/docker-squash.sh -o /usr/local/bin/docker-squash.sh
        sudo chmod +x /usr/local/bin/docker-squash.sh

    - name: Pull image to squash
      run: docker pull bibica/wordpress-wp-cli-php8.4-fpm-alpine

    - name: Squash the Docker image
      run: |
        docker-squash.sh bibica/wordpress-wp-cli-php8.4-fpm-alpine -t bibica/wordpress-wp-cli-php8.4-fpm-alpine

    - name: Build and push multi-platform image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t bibica/wordpress-wp-cli-php8.4-fpm-alpine --push .
